export const FIND_USERS = "FIND_USERS";
export const FIND_USER = "FIND_USER";
export const USER_FOLLOWERS = "USER_FOLLOWERS";
export const USER_FOLLOWING = "USER_FOLLOWING";
export const USER_REPOSITORIES = "USER_REPOSITORIES";